services:
  db:
    container_name: ghdb
    image: "mysql:9.6.0"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      retries: 3
    networks:
      - spring-mysql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  db_data:
    name: guardhub_database_volume

networks:
  spring-mysql:
    driver: bridge