spring.datasource.url=jdbc:mysql://localhost:3306/ghdb
spring.datasource.username=root
spring.datasource.password=Time@1002
server.servlet.session.timeout=600

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate